apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat-service
spec:
  type: NodePort
  selector:
    app: tomcat-app
  ports:
  - protocol: TCP
    nodePort: 30000 # 30000-32767
    port: 8880 # service port
    targetPort: 8080 # container port

# kubectl expose deployment tomcat-deployment --type=NodePort