apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat-service
spec:
  type: NodePort
  selector:
    app: tomcat-app
  ports:
  - port: 8080
    targetPort: 8080

# kubectl expose deployment tomcat-deployment --type=NodePort